const Bitmusa = require('node-bitmusa-api');
const bitmusa = new Bitmusa('dummy_key');

(async function(){

    bitmusa.fetchBalance().then(result => {
        console.log(result);
    }).catch(err => {
        console.log(err);
    });


})();

/*
{
  data: [
    {
        id: 1271,
        memberId: 73642,
        coin: {
            name: 'USDT',
            nameCn: 'USDT',
            unit: 'USDT',
            status: 0,
            minTxFee: 3.2,
            maxTxFee: 3.2,
            cnyRate: 0,
            usdRate: 1,
            enableRpc: 1,
            sort: 0,
            canSend: 1,
            canWithdraw: 1,
            canRecharge: 1,
            canTransfer: 1,
            canAutoWithdraw: 0,
            withdrawScale: 6,
            withdrawThreshold: 1,
            minWithdrawAmount: 50,
            maxWithdrawAmount: 10000,
            minRechargeAmount: 1,
            isPlatformCoin: 1,
            isToken: 1,
            hasLegal: false,
            allBalance: null,
            coldWalletAddress: '',
            hotAllBalance: null,
            blockHeight: null,
            minerFee: null,
            infolink: '',
            information: 'USDT',
            accountType: 0,
            depositAddress: null,
            memoAdjust: null,
            scanTxidWeburl: 'https://etherscan.io/tx/',
            scanAddressWeburl: 'https://etherscan.io/address/',
            visible: 1,
            testMode: 0,
            networkCoins: null,
            icon: 'https://qa-static.neonexteam.com/image/coin/USDT.svg',
            defaultIcon: 'https://qa-static.neonexteam.com/image/coin/default.svg',
            spotTradable: null
        },
        balance: 16712.50069,
        frozenBalance: 26635.9504281,
        lockedBalance: 0,
        toReleased: 0,
        networkCoin: null,
        address: '0xD7C4eBC0759FB476be46F971C88C9226d14dB7d2',
        tag: null,
        memo: null,
        isLock: 0
    },
    {
      id: 1263,
      memberId: 73642,
      coin: [Object],
      balance: 231.46758,
      frozenBalance: 0.10086,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1267,
      memberId: 73642,
      coin: [Object],
      balance: 153.8459,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1360,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1272,
      memberId: 73642,
      coin: [Object],
      balance: 471523,
      frozenBalance: 12,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: '419320',
      isLock: 0
    },
    {
      id: 1270,
      memberId: 73642,
      coin: [Object],
      balance: 495935.7,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1264,
      memberId: 73642,
      coin: [Object],
      balance: 100,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1266,
      memberId: 73642,
      coin: [Object],
      balance: 347696.9,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: '419320',
      isLock: 0
    },
    {
      id: 2036,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2032,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1489,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2319,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2320,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1490,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2321,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2322,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2034,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2323,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2324,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2325,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2033,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2326,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2327,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2031,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2035,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2328,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2037,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2329,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1491,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2330,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2331,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2332,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1492,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 1488,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2333,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2334,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    },
    {
      id: 2038,
      memberId: 73642,
      coin: [Object],
      balance: 0,
      frozenBalance: 0,
      lockedBalance: 0,
      toReleased: 0,
      networkCoin: null,
      address: '',
      tag: null,
      memo: null,
      isLock: 0
    }
  ],
  code: 0,
  message: 'SUCCESS'
}


{ code: 4000, message: 'need sign in' }

*/